[build]
  publish = "build"
  command = "npm ci --prefer-offline --no-audit && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "/api/*"
  to = "http://114.16.194.54:8000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache node_modules for faster builds
[[plugins]]
  package = "@netlify/plugin-cache"
  [plugins.inputs]
    paths = ["node_modules", ".npm"]
